"""chore: drop smart cache table

Revision ID: d07645e5d162
Revises: 9d46263bc39d
Create Date: 2026-08-26 18:31:09.683591

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd07645e5d162'
down_revision: str | Sequence[str] | None = '9d46263bc39d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cycle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generated_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('smart_cache_pkey')),
    sa.UniqueConstraint('cycle', 'topic', name=op.f('uq_smart_cache_cycle_topic'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
